# Generated by Django 4.2.2 on 2023-10-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45, unique=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('unit_measure', models.CharField(max_length=10)),
                ('date_updated', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmentcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=10)),
                ('stock_taken', models.IntegerField(default=0)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
